export type NetworkmonitorPrivilege =
  | 'CreateMonitor'
  | 'CreateProbe'
  | 'DeleteMonitor'
  | 'DeleteProbe'
  | 'GetMonitor'
  | 'GetProbe'
  | 'ListMonitors'
  | 'ListTagsForResource'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateMonitor'
  | 'UpdateProbe'