export type CodeguruSecurityPrivilege =
  | 'BatchGetFindings'
  | 'CreateScan'
  | 'CreateUploadUrl'
  | 'DeleteScansByCategory'
  | 'GetAccountConfiguration'
  | 'GetFindings'
  | 'GetMetricsSummary'
  | 'GetScan'
  | 'ListFindings'
  | 'ListFindingsMetrics'
  | 'ListScans'
  | 'ListTagsForResource'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateAccountConfiguration'
