export type DocdbElasticPrivilege =
  | 'CopyClusterSnapshot'
  | 'CreateCluster'
  | 'CreateClusterSnapshot'
  | 'DeleteCluster'
  | 'DeleteClusterSnapshot'
  | 'GetCluster'
  | 'GetClusterSnapshot'
  | 'ListClusterSnapshots'
  | 'ListClusters'
  | 'ListTagsForResource'
  | 'RestoreClusterFromSnapshot'
  | 'StartCluster'
  | 'StopCluster'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateCluster'