export type IvschatPrivilege =
  | 'CreateChatToken'
  | 'CreateLoggingConfiguration'
  | 'CreateRoom'
  | 'DeleteLoggingConfiguration'
  | 'DeleteMessage'
  | 'DeleteRoom'
  | 'DisconnectUser'
  | 'GetLoggingConfiguration'
  | 'GetRoom'
  | 'ListLoggingConfigurations'
  | 'ListRooms'
  | 'ListTagsForResource'
  | 'SendEvent'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateLoggingConfiguration'
  | 'UpdateRoom'