export type AwsMarketplaceManagementPrivilege =
  | 'GetAdditionalSellerNotificationRecipients'
  | 'GetBankAccountVerificationDetails'
  | 'GetSecondaryUserVerificationDetails'
  | 'GetSellerVerificationDetails'
  | 'PutAdditionalSellerNotificationRecipients'
  | 'PutBankAccountVerificationDetails'
  | 'PutSecondaryUserVerificationDetails'
  | 'PutSellerVerificationDetails'
  | 'uploadFiles'
  | 'viewMarketing'
  | 'viewReports'
  | 'viewSettings'
  | 'viewSupport'
