export type SchedulerPrivilege =
  | 'CreateSchedule'
  | 'CreateScheduleGroup'
  | 'DeleteSchedule'
  | 'DeleteScheduleGroup'
  | 'GetSchedule'
  | 'GetScheduleGroup'
  | 'ListScheduleGroups'
  | 'ListSchedules'
  | 'ListTagsForResource'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateSchedule'
