export type AccountPrivilege =
  | 'AcceptPrimaryEmailUpdate'
  | 'CloseAccount'
  | 'DeleteAlternateContact'
  | 'DisableRegion'
  | 'EnableRegion'
  | 'GetAccountInformation'
  | 'GetAlternateContact'
  | 'GetChallengeQuestions'
  | 'GetContactInformation'
  | 'GetPrimaryEmail'
  | 'GetRegionOptStatus'
  | 'ListRegions'
  | 'PutAlternateContact'
  | 'PutChallengeQuestions'
  | 'PutContactInformation'
  | 'StartPrimaryEmailUpdate'