export type ElementalActivationsPrivilege =
  | 'CompleteAccountRegistration'
  | 'CompleteFileUpload'
  | 'ConfirmAccount'
  | 'DownloadKickstart'
  | 'DownloadSoftware'
  | 'GenerateLicense'
  | 'GenerateLicenses'
  | 'GetArtifactGroupSoftwareVersions'
  | 'GetAsset'
  | 'GetAssets'
  | 'GetProductAdvisories'
  | 'GetSoftwareVersions'
  | 'StartFileUpload'
