export type OamPrivilege =
  | 'CreateLink'
  | 'CreateSink'
  | 'DeleteLink'
  | 'DeleteSink'
  | 'GetLink'
  | 'GetSink'
  | 'GetSinkPolicy'
  | 'ListAttachedLinks'
  | 'ListLinks'
  | 'ListSinks'
  | 'ListTagsForResource'
  | 'PutSinkPolicy'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateLink'
