export type PurchaseOrdersPrivilege =
  | 'AddPurchaseOrder'
  | 'DeletePurchaseOrder'
  | 'GetConsoleActionSetEnforced'
  | 'GetPurchaseOrder'
  | 'ListPurchaseOrderInvoices'
  | 'ListPurchaseOrders'
  | 'ListTagsForResource'
  | 'ModifyPurchaseOrders'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateConsoleActionSetEnforced'
  | 'UpdatePurchaseOrder'
  | 'UpdatePurchaseOrderStatus'
  | 'ViewPurchaseOrders'
