export type SsmQuicksetupPrivilege =
  | 'CreateConfigurationManager'
  | 'DeleteConfigurationManager'
  | 'GetConfigurationManager'
  | 'GetServiceSettings'
  | 'ListConfigurationManagers'
  | 'ListQuickSetupTypes'
  | 'ListTagsForResource'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateConfigurationDefinition'
  | 'UpdateConfigurationManager'
  | 'UpdateServiceSettings'
