export type ElementalAppliancesSoftwarePrivilege =
  | 'CompleteUpload'
  | 'CreateOrderV1'
  | 'CreateQuote'
  | 'GetAvsCorrectAddress'
  | 'GetBillingAddresses'
  | 'GetDeliveryAddressesV2'
  | 'GetOrder'
  | 'GetOrdersV2'
  | 'GetQuote'
  | 'GetTaxes'
  | 'ListQuotes'
  | 'StartUpload'
  | 'SubmitOrderV1'
  | 'UpdateQuote'