export type SimspaceweaverPrivilege =
  | 'CreateSnapshot'
  | 'DeleteApp'
  | 'DeleteSimulation'
  | 'DescribeApp'
  | 'DescribeSimulation'
  | 'ListApps'
  | 'ListSimulations'
  | 'ListTagsForResource'
  | 'StartApp'
  | 'StartClock'
  | 'StartSimulation'
  | 'StopApp'
  | 'StopClock'
  | 'StopSimulation'
  | 'TagResource'
  | 'UntagResource'
