export type BillingPrivilege =
  | 'GetBillingData'
  | 'GetBillingDetails'
  | 'GetBillingNotifications'
  | 'GetBillingPreferences'
  | 'GetContractInformation'
  | 'GetCredits'
  | 'GetIAMAccessPreference'
  | 'GetSellerOfRecord'
  | 'ListBillingViews'
  | 'PutContractInformation'
  | 'RedeemCredits'
  | 'UpdateBillingPreferences'
  | 'UpdateIAMAccessPreference'
