export type ApplicationSignalsPrivilege =
  | 'BatchGetServiceLevelObjectiveBudgetReport'
  | 'CreateServiceLevelObjective'
  | 'DeleteServiceLevelObjective'
  | 'GetService'
  | 'GetServiceLevelObjective'
  | 'ListServiceDependencies'
  | 'ListServiceDependents'
  | 'ListServiceLevelObjectives'
  | 'ListServiceOperations'
  | 'ListServices'
  | 'ListTagsForResource'
  | 'StartDiscovery'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateServiceLevelObjective'