export type IdentitySyncPrivilege =
  | 'AllowVendedLogDeliveryForResource'
  | 'CreateSyncFilter'
  | 'CreateSyncProfile'
  | 'CreateSyncTarget'
  | 'DeleteSyncFilter'
  | 'DeleteSyncProfile'
  | 'DeleteSyncTarget'
  | 'GetSyncProfile'
  | 'GetSyncTarget'
  | 'ListSyncFilters'
  | 'StartSync'
  | 'StopSync'
  | 'UpdateSyncTarget'