export type PipesPrivilege =
  | 'CreatePipe'
  | 'DeletePipe'
  | 'DescribePipe'
  | 'ListPipes'
  | 'ListTagsForResource'
  | 'StartPipe'
  | 'StopPipe'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdatePipe'