export type ArcZonalShiftPrivilege =
  | 'CancelZonalShift'
  | 'CreatePracticeRunConfiguration'
  | 'DeletePracticeRunConfiguration'
  | 'GetAutoshiftObserverNotificationStatus'
  | 'GetManagedResource'
  | 'ListAutoshifts'
  | 'ListManagedResources'
  | 'ListZonalShifts'
  | 'StartZonalShift'
  | 'UpdateAutoshiftObserverNotificationStatus'
  | 'UpdatePracticeRunConfiguration'
  | 'UpdateZonalAutoshiftConfiguration'
  | 'UpdateZonalShift'