export type ApplicationTransformationPrivilege =
  | 'GetContainerization'
  | 'GetDeployment'
  | 'GetGroupingAssessment'
  | 'GetPortingCompatibilityAssessment'
  | 'GetPortingRecommendationAssessment'
  | 'GetRuntimeAssessment'
  | 'PutLogData'
  | 'PutMetricData'
  | 'StartContainerization'
  | 'StartDeployment'
  | 'StartGroupingAssessment'
  | 'StartPortingCompatibilityAssessment'
  | 'StartPortingRecommendationAssessment'
  | 'StartRuntimeAssessment'
