export type DsDataPrivilege =
  | 'AddGroupMember'
  | 'CreateGroup'
  | 'CreateUser'
  | 'DeleteGroup'
  | 'DeleteUser'
  | 'DescribeGroup'
  | 'DescribeUser'
  | 'DisableUser'
  | 'ListGroupMembers'
  | 'ListGroups'
  | 'ListGroupsForMember'
  | 'ListUsers'
  | 'RemoveGroupMember'
  | 'SearchGroups'
  | 'SearchUsers'
  | 'UpdateGroup'
  | 'UpdateUser'