export type ServerlessrepoPrivilege =
  | 'CreateApplication'
  | 'CreateApplicationVersion'
  | 'CreateCloudFormationChangeSet'
  | 'CreateCloudFormationTemplate'
  | 'DeleteApplication'
  | 'GetApplication'
  | 'GetApplicationPolicy'
  | 'GetCloudFormationTemplate'
  | 'ListApplicationDependencies'
  | 'ListApplicationVersions'
  | 'ListApplications'
  | 'PutApplicationPolicy'
  | 'SearchApplications'
  | 'UnshareApplication'
  | 'UpdateApplication'