export type CassandraPrivilege =
  | 'Alter'
  | 'AlterMultiRegionResource'
  | 'Create'
  | 'CreateMultiRegionResource'
  | 'Drop'
  | 'DropMultiRegionResource'
  | 'Modify'
  | 'ModifyMultiRegionResource'
  | 'Restore'
  | 'RestoreMultiRegionTable'
  | 'Select'
  | 'SelectMultiRegionResource'
  | 'TagMultiRegionResource'
  | 'TagResource'
  | 'UnTagMultiRegionResource'
  | 'UntagResource'
  | 'UpdatePartitioner'