export type CloudshellPrivilege =
  | 'CreateEnvironment'
  | 'CreateSession'
  | 'DeleteEnvironment'
  | 'DescribeEnvironments'
  | 'GetEnvironmentStatus'
  | 'GetFileDownloadUrls'
  | 'GetFileUploadUrls'
  | 'PutCredentials'
  | 'StartEnvironment'
  | 'StopEnvironment'