export type StsPrivilege =
  | 'AssumeRole'
  | 'AssumeRoleWithSAML'
  | 'AssumeRoleWithWebIdentity'
  | 'DecodeAuthorizationMessage'
  | 'GetAccessKeyInfo'
  | 'GetCallerIdentity'
  | 'GetFederationToken'
  | 'GetServiceBearerToken'
  | 'GetSessionToken'
  | 'SetContext'
  | 'SetSourceIdentity'
  | 'TagSession'
