export type IotdeviceadvisorPrivilege =
  | 'CreateSuiteDefinition'
  | 'DeleteSuiteDefinition'
  | 'GetEndpoint'
  | 'GetSuiteDefinition'
  | 'GetSuiteRun'
  | 'GetSuiteRunReport'
  | 'ListSuiteDefinitions'
  | 'ListSuiteRuns'
  | 'ListTagsForResource'
  | 'StartSuiteRun'
  | 'StopSuiteRun'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateSuiteDefinition'