export type TaxPrivilege =
  | 'BatchDeleteTaxRegistration'
  | 'BatchPutTaxRegistration'
  | 'DeleteTaxRegistration'
  | 'GetExemptions'
  | 'GetTaxInfoReportingDocument'
  | 'GetTaxInheritance'
  | 'GetTaxInterview'
  | 'GetTaxRegistration'
  | 'GetTaxRegistrationDocument'
  | 'ListTaxRegistrations'
  | 'PutTaxInheritance'
  | 'PutTaxInterview'
  | 'PutTaxRegistration'
  | 'UpdateExemptions'
