export type CodeguruReviewerPrivilege =
  | 'AssociateRepository'
  | 'CreateCodeReview'
  | 'CreateConnectionToken'
  | 'DescribeCodeReview'
  | 'DescribeRecommendationFeedback'
  | 'DescribeRepositoryAssociation'
  | 'DisassociateRepository'
  | 'GetMetricsData'
  | 'ListCodeReviews'
  | 'ListRecommendationFeedback'
  | 'ListRecommendations'
  | 'ListRepositoryAssociations'
  | 'ListTagsForResource'
  | 'ListThirdPartyRepositories'
  | 'PutRecommendationFeedback'
  | 'TagResource'
  | 'UnTagResource'