export type S3expressPrivilege =
  | 'CreateBucket'
  | 'CreateSession'
  | 'DeleteBucket'
  | 'DeleteBucketPolicy'
  | 'GetBucketPolicy'
  | 'GetEncryptionConfiguration'
  | 'ListAllMyDirectoryBuckets'
  | 'PutBucketPolicy'
  | 'PutEncryptionConfiguration'