export type BugbustPrivilege =
  | 'CreateEvent'
  | 'EvaluateProfilingGroups'
  | 'GetEvent'
  | 'GetJoinEventStatus'
  | 'JoinEvent'
  | 'ListBugs'
  | 'ListEventParticipants'
  | 'ListEventScores'
  | 'ListEvents'
  | 'ListProfilingGroups'
  | 'ListPullRequests'
  | 'ListTagsForResource'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateEvent'
  | 'UpdateWorkItem'
  | 'UpdateWorkItemAdmin'
