export type ArtifactPrivilege =
  | 'AcceptAgreement'
  | 'DownloadAgreement'
  | 'Get'
  | 'GetAccountSettings'
  | 'GetReport'
  | 'GetReportMetadata'
  | 'GetTermForReport'
  | 'ListReports'
  | 'PutAccountSettings'
  | 'TerminateAgreement'
