export type IqPermissionPrivilege =
  | 'ApproveAccessGrant'
  | 'ApprovePermissionRequest'
  | 'AssumePermissionRole'
  | 'CreatePermissionRequest'
  | 'GetPermissionRequest'
  | 'ListPermissionRequests'
  | 'RejectPermissionRequest'
  | 'RevokePermissionRequest'
  | 'WithdrawPermissionRequest'
