export type InternetmonitorPrivilege =
  | 'CreateMonitor'
  | 'DeleteMonitor'
  | 'GetHealthEvent'
  | 'GetInternetEvent'
  | 'GetMonitor'
  | 'GetQueryResults'
  | 'GetQueryStatus'
  | 'Link'
  | 'ListHealthEvents'
  | 'ListInternetEvents'
  | 'ListMonitors'
  | 'ListTagsForResource'
  | 'StartQuery'
  | 'StopQuery'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateMonitor'
