export type KendraRankingPrivilege =
  | 'CreateRescoreExecutionPlan'
  | 'DeleteRescoreExecutionPlan'
  | 'DescribeRescoreExecutionPlan'
  | 'ListRescoreExecutionPlans'
  | 'ListTagsForResource'
  | 'Rescore'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateRescoreExecutionPlan'
