export type SupportappPrivilege =
  | 'CreateSlackChannelConfiguration'
  | 'DeleteAccountAlias'
  | 'DeleteSlackChannelConfiguration'
  | 'DeleteSlackWorkspaceConfiguration'
  | 'DescribeSlackChannels'
  | 'GetAccountAlias'
  | 'GetSlackOauthParameters'
  | 'ListSlackChannelConfigurations'
  | 'ListSlackWorkspaceConfigurations'
  | 'PutAccountAlias'
  | 'RedeemSlackOauthCode'
  | 'RegisterSlackWorkspaceForOrganization'
  | 'UpdateSlackChannelConfiguration'
