export type PaymentsPrivilege =
  | 'CreatePaymentInstrument'
  | 'DeletePaymentInstrument'
  | 'GetPaymentInstrument'
  | 'GetPaymentStatus'
  | 'ListPaymentInstruments'
  | 'ListPaymentPreferences'
  | 'ListTagsForResource'
  | 'MakePayment'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdatePaymentInstrument'
  | 'UpdatePaymentPreferences'
