export type TsPrivilege =
  | 'GetExecution'
  | 'GetExecutionOutput'
  | 'GetTool'
  | 'ListExecutions'
  | 'ListTagsForResource'
  | 'ListTools'
  | 'StartExecution'
  | 'TagResource'
  | 'UntagResource'
