export type KafkaconnectPrivilege =
  | 'CreateConnector'
  | 'CreateCustomPlugin'
  | 'CreateWorkerConfiguration'
  | 'DeleteConnector'
  | 'DeleteCustomPlugin'
  | 'DeleteWorkerConfiguration'
  | 'DescribeConnector'
  | 'DescribeCustomPlugin'
  | 'DescribeWorkerConfiguration'
  | 'ListConnectors'
  | 'ListCustomPlugins'
  | 'ListTagsForResource'
  | 'ListWorkerConfigurations'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateConnector'
