export type RumPrivilege =
  | 'BatchCreateRumMetricDefinitions'
  | 'BatchDeleteRumMetricDefinitions'
  | 'BatchGetRumMetricDefinitions'
  | 'CreateAppMonitor'
  | 'DeleteAppMonitor'
  | 'DeleteRumMetricsDestination'
  | 'GetAppMonitor'
  | 'GetAppMonitorData'
  | 'ListAppMonitors'
  | 'ListRumMetricsDestinations'
  | 'ListTagsForResource'
  | 'PutRumEvents'
  | 'PutRumMetricsDestination'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateAppMonitor'
  | 'UpdateRumMetricDefinition'
