export type HealthPrivilege =
  | 'DescribeAffectedAccountsForOrganization'
  | 'DescribeAffectedEntities'
  | 'DescribeAffectedEntitiesForOrganization'
  | 'DescribeEntityAggregates'
  | 'DescribeEntityAggregatesForOrganization'
  | 'DescribeEventAggregates'
  | 'DescribeEventDetails'
  | 'DescribeEventDetailsForOrganization'
  | 'DescribeEventTypes'
  | 'DescribeEvents'
  | 'DescribeEventsForOrganization'
  | 'DescribeHealthServiceStatusForOrganization'
  | 'DisableHealthServiceAccessForOrganization'
  | 'EnableHealthServiceAccessForOrganization'