export type BudgetsPrivilege =
  | 'CreateBudgetAction'
  | 'DeleteBudgetAction'
  | 'DescribeBudgetAction'
  | 'DescribeBudgetActionHistories'
  | 'DescribeBudgetActionsForAccount'
  | 'DescribeBudgetActionsForBudget'
  | 'ExecuteBudgetAction'
  | 'ListTagsForResource'
  | 'ModifyBudget'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateBudgetAction'
  | 'ViewBudget'
