export type SagemakerGroundtruthSyntheticPrivilege =
  | 'CreateProject'
  | 'DeleteProject'
  | 'GetAccountDetails'
  | 'GetBatch'
  | 'GetProject'
  | 'ListBatchDataTransfers'
  | 'ListBatchSummaries'
  | 'ListProjectDataTransfers'
  | 'ListProjectSummaries'
  | 'StartBatchDataTransfer'
  | 'StartProjectDataTransfer'
  | 'UpdateBatch'