export type AcmPrivilege =
  | 'AddTagsToCertificate'
  | 'DeleteCertificate'
  | 'DescribeCertificate'
  | 'ExportCertificate'
  | 'GetAccountConfiguration'
  | 'GetCertificate'
  | 'ImportCertificate'
  | 'ListCertificates'
  | 'ListTagsForCertificate'
  | 'PutAccountConfiguration'
  | 'RemoveTagsFromCertificate'
  | 'RenewCertificate'
  | 'RequestCertificate'
  | 'ResendValidationEmail'
  | 'UpdateCertificateOptions'