export type PiPrivilege =
  | 'CreatePerformanceAnalysisReport'
  | 'DeletePerformanceAnalysisReport'
  | 'DescribeDimensionKeys'
  | 'GetDimensionKeyDetails'
  | 'GetPerformanceAnalysisReport'
  | 'GetResourceMetadata'
  | 'GetResourceMetrics'
  | 'ListAvailableResourceDimensions'
  | 'ListAvailableResourceMetrics'
  | 'ListPerformanceAnalysisReports'
  | 'ListTagsForResource'
  | 'TagResource'
  | 'UntagResource'
