export type TimestreamInfluxdbPrivilege =
  | 'CreateDbInstance'
  | 'CreateDbParameterGroup'
  | 'DeleteDbInstance'
  | 'GetDbInstance'
  | 'GetDbParameterGroup'
  | 'ListDbInstances'
  | 'ListDbParameterGroups'
  | 'ListTagsForResource'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateDbInstance'