export type PollyPrivilege =
  | 'DeleteLexicon'
  | 'DescribeVoices'
  | 'GetLexicon'
  | 'GetSpeechSynthesisTask'
  | 'ListLexicons'
  | 'ListSpeechSynthesisTasks'
  | 'PutLexicon'
  | 'StartSpeechSynthesisTask'
  | 'SynthesizeSpeech'
