export type AwsPortalPrivilege =
  | 'GetConsoleActionSetEnforced'
  | 'ModifyAccount'
  | 'ModifyBilling'
  | 'ModifyPaymentMethods'
  | 'UpdateConsoleActionSetEnforced'
  | 'ViewAccount'
  | 'ViewBilling'
  | 'ViewPaymentMethods'
  | 'ViewUsage'
