export type GroundtruthlabelingPrivilege =
  | 'AssociatePatchToManifestJob'
  | 'CreateBatch'
  | 'CreateIntakeForm'
  | 'CreateProject'
  | 'CreateWorkflowDefinition'
  | 'DescribeConsoleJob'
  | 'GenerateLIDARPreviewTaskConfigJob'
  | 'GetBatch'
  | 'GetIntakeFormStatus'
  | 'ListBatches'
  | 'ListDatasetObjects'
  | 'ListProjects'
  | 'RunFilterOrSampleDatasetJob'
  | 'RunGenerateManifestByCrawlingJob'
  | 'RunGenerateManifestMetricsJob'
  | 'UpdateBatch'
