export type ManagedblockchainQueryPrivilege =
  | 'BatchGetTokenBalance'
  | 'GetAssetContract'
  | 'GetTokenBalance'
  | 'GetTransaction'
  | 'ListAssetContracts'
  | 'ListFilteredTransactionEvents'
  | 'ListTokenBalances'
  | 'ListTransactionEvents'
  | 'ListTransactions'