export type ApplicationAutoscalingPrivilege =
  | 'DeleteScalingPolicy'
  | 'DeleteScheduledAction'
  | 'DeregisterScalableTarget'
  | 'DescribeScalableTargets'
  | 'DescribeScalingActivities'
  | 'DescribeScalingPolicies'
  | 'DescribeScheduledActions'
  | 'ListTagsForResource'
  | 'PutScalingPolicy'
  | 'PutScheduledAction'
  | 'RegisterScalableTarget'
  | 'TagResource'
  | 'UntagResource'