export type NotificationsContactsPrivilege =
  | 'ActivateEmailContact'
  | 'CreateEmailContact'
  | 'DeleteEmailContact'
  | 'GetEmailContact'
  | 'ListEmailContacts'
  | 'ListTagsForResource'
  | 'SendActivationCode'
  | 'TagResource'
  | 'UntagResource'
