export type SnowDeviceManagementPrivilege =
  | 'CancelTask'
  | 'CreateTask'
  | 'DescribeDevice'
  | 'DescribeDeviceEc2Instances'
  | 'DescribeExecution'
  | 'DescribeTask'
  | 'ListDeviceResources'
  | 'ListDevices'
  | 'ListExecutions'
  | 'ListTagsForResource'
  | 'ListTasks'
  | 'TagResource'
  | 'UntagResource'
