export type OsisPrivilege =
  | 'CreatePipeline'
  | 'DeletePipeline'
  | 'GetPipeline'
  | 'GetPipelineBlueprint'
  | 'GetPipelineChangeProgress'
  | 'Ingest'
  | 'ListPipelineBlueprints'
  | 'ListPipelines'
  | 'ListTagsForResource'
  | 'StartPipeline'
  | 'StopPipeline'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdatePipeline'
  | 'ValidatePipeline'