export type DbqmsPrivilege =
  | 'CreateFavoriteQuery'
  | 'CreateQueryHistory'
  | 'CreateTab'
  | 'DeleteFavoriteQueries'
  | 'DeleteQueryHistory'
  | 'DeleteTab'
  | 'DescribeFavoriteQueries'
  | 'DescribeQueryHistory'
  | 'DescribeTabs'
  | 'GetQueryString'
  | 'UpdateFavoriteQuery'
  | 'UpdateQueryHistory'
  | 'UpdateTab'