export type SavingsplansPrivilege =
  | 'CreateSavingsPlan'
  | 'DeleteQueuedSavingsPlan'
  | 'DescribeSavingsPlanRates'
  | 'DescribeSavingsPlans'
  | 'DescribeSavingsPlansOfferingRates'
  | 'DescribeSavingsPlansOfferings'
  | 'ListTagsForResource'
  | 'ReturnSavingsPlan'
  | 'TagResource'
  | 'UntagResource'
