export type ThinclientPrivilege =
  | 'CreateEnvironment'
  | 'DeleteDevice'
  | 'DeleteEnvironment'
  | 'DeregisterDevice'
  | 'GetDevice'
  | 'GetEnvironment'
  | 'GetSoftwareSet'
  | 'ListDeviceSessions'
  | 'ListDevices'
  | 'ListEnvironments'
  | 'ListSoftwareSets'
  | 'ListTagsForResource'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateDevice'
  | 'UpdateEnvironment'
  | 'UpdateSoftwareSet'
