export type BcmDataExportsPrivilege =
  | 'CreateExport'
  | 'DeleteExport'
  | 'GetExecution'
  | 'GetExport'
  | 'GetTable'
  | 'ListExecutions'
  | 'ListExports'
  | 'ListTables'
  | 'ListTagsForResource'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateExport'
