export type BackupStoragePrivilege =
  | 'CommitBackupJob'
  | 'DeleteObjects'
  | 'DescribeBackupJob'
  | 'GetBaseBackup'
  | 'GetChunk'
  | 'GetIncrementalBaseBackup'
  | 'GetObjectMetadata'
  | 'ListChunks'
  | 'ListObjects'
  | 'MountCapsule'
  | 'NotifyObjectComplete'
  | 'PutChunk'
  | 'PutObject'
  | 'StartObject'
  | 'UpdateObjectComplete'