export type LicenseManagerUserSubscriptionsPrivilege =
  | 'AssociateUser'
  | 'DeregisterIdentityProvider'
  | 'DisassociateUser'
  | 'ListIdentityProviders'
  | 'ListInstances'
  | 'ListProductSubscriptions'
  | 'ListUserAssociations'
  | 'RegisterIdentityProvider'
  | 'StartProductSubscription'
  | 'StopProductSubscription'
  | 'UpdateIdentityProviderSettings'
