export type BraketPrivilege =
  | 'AcceptUserAgreement'
  | 'AccessBraketFeature'
  | 'CancelJob'
  | 'CancelQuantumTask'
  | 'CreateJob'
  | 'CreateQuantumTask'
  | 'GetDevice'
  | 'GetJob'
  | 'GetQuantumTask'
  | 'GetServiceLinkedRoleStatus'
  | 'GetUserAgreementStatus'
  | 'ListTagsForResource'
  | 'SearchDevices'
  | 'SearchJobs'
  | 'SearchQuantumTasks'
  | 'TagResource'
  | 'UntagResource'