export type LicenseManagerLinuxSubscriptionsPrivilege =
  | 'DeregisterSubscriptionProvider'
  | 'GetRegisteredSubscriptionProvider'
  | 'GetServiceSettings'
  | 'ListLinuxSubscriptionInstances'
  | 'ListLinuxSubscriptions'
  | 'ListRegisteredSubscriptionProviders'
  | 'ListTagsForResource'
  | 'RegisterSubscriptionProvider'
  | 'TagResource'
  | 'UntagResource'
  | 'UpdateServiceSettings'
